/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_upscale_PsocMapper */

#ifndef _Included_com_upscale_PsocMapper
#define _Included_com_upscale_PsocMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_upscale_PsocMapper
 * Method:    GenerateTaskTable
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_upscale_PsocMapper_GenerateTaskTable
  (JNIEnv *, jclass, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
