/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hipert_hg_modelToCode_PsocMapper */

#ifndef _Included_hipert_hg_modelToCode_PsocMapper
#define _Included_hipert_hg_modelToCode_PsocMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hipert_hg_modelToCode_PsocMapper
 * Method:    GenerateTaskTable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hipert_hg_modelToCode_PsocMapper_GenerateTaskTable
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
